import { COATING_LABELS, COATING_RATES } from '../types/door';
import { CoatingType } from '../backend';

export interface CoatingBlockData {
  coatingType: CoatingType;
  rate: number;
  totalSqFt: number;
  totalAmount: number;
  rows: {
    door: {
      actualHeightInches: number;
      actualWidthInches: number;
      catalogueHeight: number;
      catalogueWidth: number;
      quantity: number;
    };
    sqFt: number;
    lineTotal: number;
  }[];
}

function formatInches(val: number): string {
  if (val % 1 === 0) return `${val}"`;
  return `${val.toFixed(3).replace(/\.?0+$/, '')}"`;
}

export function formatWhatsAppMessage(
  coatingBlocks: CoatingBlockData[],
  customerName: string,
  mobileNumber: string
): string {
  const date = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

  let msg = `🚪 *DOOR QUOTATION*\n`;
  msg += `Date: ${date}\n`;
  msg += `${'─'.repeat(32)}\n`;

  if (customerName.trim()) {
    msg += `Customer: *${customerName.trim()}*\n`;
  }
  if (mobileNumber.trim()) {
    msg += `Mobile: ${mobileNumber.trim()}\n`;
  }
  msg += `${'─'.repeat(32)}\n\n`;

  // Per-door summary (all coatings for each door)
  if (coatingBlocks.length > 0 && coatingBlocks[0].rows.length > 0) {
    const numDoors = coatingBlocks[0].rows.length;
    msg += `*DOOR DETAILS*\n`;
    msg += `${'─'.repeat(24)}\n`;

    for (let i = 0; i < numDoors; i++) {
      const firstRow = coatingBlocks[0].rows[i];
      const door = firstRow.door;
      const actualSize = `${formatInches(door.actualWidthInches)} × ${formatInches(door.actualHeightInches)}`;
      const catSize = `${door.catalogueWidth}" × ${door.catalogueHeight}"`;

      msg += `${i + 1}. Actual: ${actualSize} → Catalogue: ${catSize}\n`;
      msg += `   Thickness: 30 mm | Sq.ft: ${firstRow.sqFt.toFixed(2)} | Qty: ${door.quantity}\n`;

      for (const block of coatingBlocks) {
        const row = block.rows[i];
        msg += `   ${COATING_LABELS[block.coatingType]}: ₹${block.rate}/sq.ft → ₹${row.lineTotal.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}\n`;
      }
      msg += `\n`;
    }
  }

  // Coating type totals
  msg += `${'─'.repeat(32)}\n`;
  msg += `*GRAND TOTAL BY COATING TYPE*\n`;
  msg += `${'─'.repeat(32)}\n`;

  for (const block of coatingBlocks) {
    msg += `*${COATING_LABELS[block.coatingType]}*\n`;
    msg += `  Rate: ₹${block.rate}/sq.ft | Total Sq.ft: ${block.totalSqFt.toFixed(2)}\n`;
    msg += `  Total: ₹${block.totalAmount.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}\n\n`;
  }

  msg += `${'─'.repeat(32)}\n`;
  msg += `_Generated by Door Quotation Calculator_`;

  return encodeURIComponent(msg);
}
