/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CoatingType = IDL.Variant({
  'doubleSagwanpatti' : IDL.Null,
  'double' : IDL.Null,
  'laminate' : IDL.Null,
  'single' : IDL.Null,
});

export const idlService = IDL.Service({
  'getCoatingRate' : IDL.Func([CoatingType], [IDL.Nat], ['query']),
  'getDoubleRate' : IDL.Func([], [IDL.Nat], ['query']),
  'getDoubleSagwanpattiRate' : IDL.Func([], [IDL.Nat], ['query']),
  'getLaminateRate' : IDL.Func([], [IDL.Nat], ['query']),
  'getSingleRate' : IDL.Func([], [IDL.Nat], ['query']),
  'updateCoatingRate' : IDL.Func([CoatingType, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CoatingType = IDL.Variant({
    'doubleSagwanpatti' : IDL.Null,
    'double' : IDL.Null,
    'laminate' : IDL.Null,
    'single' : IDL.Null,
  });
  
  return IDL.Service({
    'getCoatingRate' : IDL.Func([CoatingType], [IDL.Nat], ['query']),
    'getDoubleRate' : IDL.Func([], [IDL.Nat], ['query']),
    'getDoubleSagwanpattiRate' : IDL.Func([], [IDL.Nat], ['query']),
    'getLaminateRate' : IDL.Func([], [IDL.Nat], ['query']),
    'getSingleRate' : IDL.Func([], [IDL.Nat], ['query']),
    'updateCoatingRate' : IDL.Func([CoatingType, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };